In [37]:
# rename the file from .data to .csv
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
# To split in test and train
from sklearn.model_selection import train_test_split

In [38]:
# header none - to prevent taking data as the names of columns
db = pd.read_csv('pima-indians-diabetes.csv',header=None)

In [39]:
db.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [40]:
db.describe()
# bmi,bp = 0 is very strange
# insulin depicts outlierish behaviour

0           1           2           3           4           5   
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000  \
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

                6           7           8  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [41]:
db.columns = ['pregnant','glucose','bloodpressure',
              'skinfold','insulin','Bmi',
              'pedigree','Age','Class']

In [42]:
db.head()

pregnant  glucose  bloodpressure  skinfold  insulin   Bmi  pedigree  Age   
0         6      148             72        35        0  33.6     0.627   50  \
1         1       85             66        29        0  26.6     0.351   31   
2         8      183             64         0        0  23.3     0.672   32   
3         1       89             66        23       94  28.1     0.167   21   
4         0      137             40        35      168  43.1     2.288   33   

   Class  
0      1  
1      0  
2      1  
3      0  
4      1

In [43]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   pregnant       768 non-null    int64  
 1   glucose        768 non-null    int64  
 2   bloodpressure  768 non-null    int64  
 3   skinfold       768 non-null    int64  
 4   insulin        768 non-null    int64  
 5   Bmi            768 non-null    float64
 6   pedigree       768 non-null    float64
 7   Age            768 non-null    int64  
 8   Class          768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [44]:
X = db.drop(['Class'],axis=1)
X

pregnant  glucose  bloodpressure  skinfold  insulin   Bmi  pedigree  Age
0           6      148             72        35        0  33.6     0.627   50
1           1       85             66        29        0  26.6     0.351   31
2           8      183             64         0        0  23.3     0.672   32
3           1       89             66        23       94  28.1     0.167   21
4           0      137             40        35      168  43.1     2.288   33
..        ...      ...            ...       ...      ...   ...       ...  ...
763        10      101             76        48      180  32.9     0.171   63
764         2      122             70        27        0  36.8     0.340   27
765         5      121             72        23      112  26.2     0.245   30
766         1      126             60         0        0  30.1     0.349   47
767         1       93             70        31        0  30.4     0.315   23

[768 rows x 8 columns]

In [45]:
y = db[['Class']]
y

Class
0        1
1        0
2        1
3        0
4        1
..     ...
763      0
764      0
765      0
766      1
767      0

[768 rows x 1 columns]

In [46]:
db['Class'].value_counts()
# sample can be biased as the classes are highly imbalanced

Class
0    500
1    268
Name: count, dtype: int64

In [57]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3, stratify=y, random_state=5)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(537, 8) (231, 8) (537,) (231,)


In [48]:
# observe stratify
y_train['Class'].value_counts()
y_test['Class'].value_counts()

Class
0    150
1     81
Name: count, dtype: int64

Logistic Regression Model

In [58]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [50]:
# working on warning
# convert X and y into numpy arrays
X = X.values
type(X)

numpy.ndarray

In [51]:
y = y.values.ravel()
y.shape

(768,)

In [59]:
predict = lr.predict(X_test)

In [60]:
predict

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0])

In [61]:
y_test


array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0])

In [66]:
# since both predict and y_test are 1d arrays comparison can be done
# accuracy
(y_test == predict).sum()/len(predict)

0.7575757575757576

In [67]:
# accuracy calculation using sklearn
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predict)

0.7575757575757576

KNN MODEL

In [92]:
# default n_neighbors=5
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [93]:
predict_knn = knn.predict(X_test)

In [94]:
predict_knn

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0])

In [95]:
accuracy_score(y_test,predict_knn)

0.7402597402597403