### Reversing

In [2]:
import numpy as np

In [2]:
np_arr = np.linspace(1,10)
np_arr
#linspace = equally spaced, 50 = default no of elements


array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [3]:
np_arr.shape


(50,)

In [10]:
np_arr = np.random.randint(1,100,10)
np_arr

array([16, 99,  8, 78, 30, 33, 20, 90,  2, 95])

In [6]:
np_arr.sort()
np_arr = np.flip(np_arr)
np_arr

array([9, 8, 8, 7, 6, 5, 5, 4, 2, 2])

Reversing using slicing

In [11]:
np_arr[5:1:-1]

array([33, 30, 78,  8])

In [12]:
np_arr[:]

array([16, 99,  8, 78, 30, 33, 20, 90,  2, 95])

In [13]:
np_arr[::-1]

array([95,  2, 90, 20, 33, 30, 78,  8, 99, 16])

Reverse sort

In [16]:
sorted(np_arr, reverse=True)

[99, 95, 90, 78, 33, 30, 20, 16, 8, 2]

### more mathematical functions

In [19]:
numpyarr = np.random.uniform(1,10, size=10)
numpyarr

array([6.95191968, 1.75783622, 3.04087357, 1.0181094 , 5.64782545,
       3.16758824, 5.89645411, 4.0406616 , 6.11591667, 8.94750315])

In [20]:
# floor function
np.floor(numpyarr)

array([6., 1., 3., 1., 5., 3., 5., 4., 6., 8.])

In [21]:
np.ceil(numpyarr)

array([7., 2., 4., 2., 6., 4., 6., 5., 7., 9.])

In [22]:
# e value 
np.exp(numpyarr)

array([1.04515416e+03, 5.79987416e+00, 2.09235133e+01, 2.76795671e+00,
       2.83673931e+02, 2.37501357e+01, 3.63745377e+02, 5.68639514e+01,
       4.53011118e+02, 7.68867043e+03])

### Shape manipulation functions

In [25]:
np_arr

array([ 2,  8, 16, 20, 30, 33, 78, 90, 95, 99])

In [31]:
print(np_arr.size)
print(np_arr.shape)
print(np_arr.ndim)

10
(10,)
1


In [56]:
np_arr.reshape(5,2)

array([[ 2,  8],
       [16, 20],
       [30, 33],
       [78, 90],
       [95, 99]])

In [54]:
np_arr_2d

array([[ 2,  8],
       [16, 20],
       [30, 33],
       [78, 90],
       [95, 99]])

In [57]:
np_arr

array([ 2,  8, 16, 20, 30, 33, 78, 90, 95, 99])

In [45]:
#pipelining
num_3d = np.random.random(40).reshape(4,2,5)

In [46]:
num_3d

array([[[0.50876661, 0.41482683, 0.35183335, 0.12025033, 0.33154227],
        [0.92587965, 0.19802098, 0.24200052, 0.44097781, 0.18186717]],

       [[0.51316087, 0.7205466 , 0.80555548, 0.09640065, 0.40933508],
        [0.40979361, 0.29645711, 0.79162392, 0.82808586, 0.27182337]],

       [[0.60438111, 0.07572811, 0.35300188, 0.9279587 , 0.49170823],
        [0.38269228, 0.84786506, 0.24116006, 0.62690222, 0.17350623]],

       [[0.6572873 , 0.83840373, 0.58496622, 0.91124618, 0.33110082],
        [0.92497565, 0.53654858, 0.64997305, 0.23641088, 0.34464817]]])

In [48]:
# flattening
np_arr_2d.flatten()

array([ 2,  8, 16, 20, 30, 33, 78, 90, 95, 99])

In [49]:
np_arr_2d

array([[ 2,  8],
       [16, 20],
       [30, 33],
       [78, 90],
       [95, 99]])

In [50]:
np_arr_2d.resize(2,5)

In [51]:
np_arr_2d

array([[ 2,  8, 16, 20, 30],
       [33, 78, 90, 95, 99]])

In [52]:
np_arr_2d.flatten()

array([ 2,  8, 16, 20, 30, 33, 78, 90, 95, 99])

### interesting functions in numpy

In [58]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [59]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [64]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [66]:
np.transpose(arr)

array([1, 2, 3, 4])

### Pandas 

In [2]:
import numpy as np
import pandas as pd

In [2]:
#using series
array = pd.Series(np.array([35,44,22]))
array

0    35
1    44
2    22
dtype: int64

In [44]:
#using dict
d = {'srk':4,'kajol':5, 'kiran':3}

In [45]:
array2 = pd.Series(d)
array2['srk']

4

In [16]:
#using scalar (single value)
max_marks = pd.Series(np.random.randint(50,51,10))
max_marks

0    50
1    50
2    50
3    50
4    50
5    50
6    50
7    50
8    50
9    50
dtype: int64

In [17]:
max_marks2 = pd.Series([50]*10)
max_marks2

0    50
1    50
2    50
3    50
4    50
5    50
6    50
7    50
8    50
9    50
dtype: int64

In [20]:
list2 = [50]*2
list2

[50, 50]

In [42]:
max_marks3 = pd.Series(50 , index=range(10))
max_marks3

0    50
1    50
2    50
3    50
4    50
5    50
6    50
7    50
8    50
9    50
dtype: int64

In [48]:
max_marks3 = pd.Series(range(10) , index=range(10,20))
max_marks3[17]

7

### Trouble to access by 0 when index is labelled by integer

In [3]:
max_marks3 = pd.Series(range(10) , index=range(10,20))
max_marks3[0]

KeyError: 0

In [50]:
# resolve by iloc
max_marks3.iloc[0]

0

In [47]:
# accessing elements in series
array2 = pd.Series(d)
array2[-1]

3

In [16]:
# understading iloc and loc
marks= pd.Series(np.random.randint(30,50,10), index=range(100,110))
marks

100    38
101    39
102    38
103    31
104    43
105    41
106    49
107    40
108    34
109    30
dtype: int64

In [17]:
marks[100]

38

In [26]:
#index with implicit, natural indexing
marks.iloc[0]

38

In [59]:
marks.loc[100]
#made because sometimes keys and indices both are numbers, so you might call the data.
# loc means value of the label
# can't use this when label is string

36

### Vectorizing operations in series

In [60]:
s1 = pd.Series(np.random.uniform(10,30,5), index=['a','b','c','d','e'])
s2 = pd.Series(np.random.uniform(10,30,5), index=['a','b','c','e','f'])
print(s1+s2)

a    23.502390
b    40.156533
c    54.884396
d          NaN
e    46.853724
f          NaN
dtype: float64


In [61]:
45 + np.nan

nan

### DataFrame

In [63]:
df = pd.DataFrame({'age':np.random.randint(18,65,10), 'names':['student']*10})
df
# name is associated to column
# no data type column
# Inside df funcion call a dictionary w the individual column names and
# in each column past a list of values
# make list of values are equal in every column 

age    names
0   39  student
1   35  student
2   43  student
3   21  student
4   53  student
5   50  student
6   63  student
7   29  student
8   30  student
9   35  student

In [84]:
df2 = pd.DataFrame({'age':np.random.randint(18,65,10),
                   'names':['student']*10},
                  index=list('abcdefghij'))
df2

age    names
a   30  student
b   57  student
c   27  student
d   28  student
e   27  student
f   55  student
g   50  student
h   47  student
i   60  student
j   49  student

In [68]:
df3 = pd.DataFrame({'age':np.random.randint(18,65,10),
                   'names':['student']*10},
                  index=range(100,110))
df3

age    names
100   44  student
101   62  student
102   24  student
103   57  student
104   21  student
105   33  student
106   28  student
107   38  student
108   19  student
109   25  student

### DataFrame from dict

In [66]:
olympic = pd.DataFrame({'London':{2012:205,2008:206},'Beijing':{2012:203,2008:204}})
olympic
# nan gets accomodated

London  Beijing
2012     205      203
2008     206      204

In [70]:
# access values
df3.age
# output in the form of series

100    44
101    62
102    24
103    57
104    21
105    33
106    28
107    38
108    19
109    25
Name: age, dtype: int64

In [4]:
df = pd.DataFrame({'age':np.random.randint(18,65,10), 'names':['student']*10, 'rollno':range(110,120)})
df

age    names  rollno
0   42  student     110
1   59  student     111
2   29  student     112
3   53  student     113
4   62  student     114
5   59  student     115
6   34  student     116
7   51  student     117
8   54  student     118
9   63  student     119

In [5]:
# subset of df
# pass the column names as a list rather than passing dimensions
df[['age','rollno']]

age  rollno
0   42     110
1   59     111
2   29     112
3   53     113
4   62     114
5   59     115
6   34     116
7   51     117
8   54     118
9   63     119

In [8]:
# how to access rows
df.loc[8]

age            54
names     student
rollno        118
Name: 8, dtype: object

Practice federal data

In [10]:
# load csv data as a dataframe 
df_fed = pd.read_csv('faa_ai_prelim.csv')
df_fed.head()

UPDATED ENTRY_DATE EVENT_LCL_DATE EVENT_LCL_TIME LOC_CITY_NAME   
0      No  19-FEB-16      19-FEB-16      00:45:00Z    MARSHVILLE  \
1      No  19-FEB-16      18-FEB-16      23:55:00Z     TAVERNIER   
2      No  19-FEB-16      18-FEB-16      22:14:00Z       TRENTON   
3      No  19-FEB-16      18-FEB-16      17:10:00Z     ASHEVILLE   
4      No  19-FEB-16      18-FEB-16      00:26:00Z     TALKEETNA   

   LOC_STATE_NAME LOC_CNTRY_NAME   
0  North Carolina            NaN  \
1         Florida            NaN   
2      New Jersey            NaN   
3  North Carolina            NaN   
4          Alaska            NaN   

                                            RMK_TEXT EVENT_TYPE_DESC   
0  AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...        Accident  \
1  AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...        Incident   
2  AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...        Incident   
3  AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...        Incident   
4  AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...        Incident   

                  FSDO_DESC  ... PAX_INJ_NONE PAX_INJ_MINOR PAX_INJ_SERIOUS   
0     FAA Charlotte FSDO-68  ...          NaN           NaN             NaN  \
1         FAA Miami FSDO-19  ...          NaN           NaN             NaN   
2  FAA Philadelphia FSDO-17  ...          NaN           NaN             NaN   
3     FAA Charlotte FSDO-68  ...          NaN           NaN             NaN   
4     FAA Anchorage FSDO-03  ...          NaN           1.0             NaN   

  PAX_INJ_FATAL PAX_INJ_UNK  GRND_INJ_NONE GRND_INJ_MINOR GRND_INJ_SERIOUS   
0           NaN         NaN            NaN            NaN              NaN  \
1           NaN         NaN            NaN            NaN              NaN   
2           NaN         NaN            NaN            NaN              NaN   
3           NaN         NaN            NaN            NaN              NaN   
4           NaN         NaN            NaN            NaN              NaN   

  GRND_INJ_FATAL  GRND_INJ_UNK  
0            NaN           NaN  
1            NaN           NaN  
2            NaN           NaN  
3            NaN           NaN  
4            NaN           NaN  

[5 rows x 42 columns]

In [21]:
# columns are attributes, charactertics of df
# head is a function, you're performing an action
list1 = df_fed.columns
list1

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'],
      dtype='object')

In [13]:
df_fed.shape

(83, 42)

In [14]:
df_fed[['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME']]

UPDATED ENTRY_DATE EVENT_LCL_DATE EVENT_LCL_TIME LOC_CITY_NAME   
0       No  19-FEB-16      19-FEB-16      00:45:00Z    MARSHVILLE  \
1       No  19-FEB-16      18-FEB-16      23:55:00Z     TAVERNIER   
2       No  19-FEB-16      18-FEB-16      22:14:00Z       TRENTON   
3       No  19-FEB-16      18-FEB-16      17:10:00Z     ASHEVILLE   
4       No  19-FEB-16      18-FEB-16      00:26:00Z     TALKEETNA   
..     ...        ...            ...            ...           ...   
78      No  08-FEB-16      31-DEC-15      17:00:00Z   SAN ANTONIO   
79      No  08-FEB-16      05-FEB-16      11:17:00Z      MARICOPA   
80      No  08-FEB-16      05-FEB-16      23:02:00Z     SAN PEDRO   
81      No  08-FEB-16      05-FEB-16      23:02:00Z     SAN PEDRO   
82     Yes  02-FEB-16      02-FEB-16      01:52:00Z        MOBILE   

    LOC_STATE_NAME  
0   North Carolina  
1          Florida  
2       New Jersey  
3   North Carolina  
4           Alaska  
..             ...  
78           Texas  
79         Arizona  
80      California  
81      California  
82         Alabama  

[83 rows x 6 columns]

In [24]:
# want columns from 15 to 20
df_fed[list1[15:21]]

ACFT_MISSING_FLAG ACFT_DMG_DESC FLT_ACTIVITY       FLT_PHASE  FAR_PART   
0                 NaN       Unknown          NaN   UNKNOWN (UNK)       NaN  \
1                 NaN       Unknown          NaN   LANDING (LDG)       NaN   
2                 NaN         Minor          NaN  APPROACH (APR)       NaN   
3                 NaN       Unknown          NaN   LANDING (LDG)       NaN   
4                 NaN         Minor          NaN   LANDING (LDG)       NaN   
..                ...           ...          ...             ...       ...   
78                NaN   Substantial          NaN   LANDING (LDG)       NaN   
79                NaN     Destroyed          NaN   UNKNOWN (UNK)       NaN   
80                NaN     Destroyed          NaN   UNKNOWN (UNK)       NaN   
81                NaN     Destroyed          NaN   UNKNOWN (UNK)       NaN   
82                NaN       Unknown          NaN   UNKNOWN (UNK)       NaN   

   MAX_INJ_LVL  
0        Fatal  
1          NaN  
2          NaN  
3          NaN  
4        Minor  
..         ...  
78         NaN  
79       Fatal  
80       Fatal  
81       Fatal  
82       Fatal  

[83 rows x 6 columns]